'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import { Provider } from "react-redux";
import store from "@/lib/store/store";
//for toast messages
import { Toaster } from 'react-hot-toast'
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const pathname = usePathname();

  // List of routes where navbar should be hidden
  const hideNavbarOn = ['/auth/login', '/auth/register', '/auth/forgot-password','/auth/reset-password'];

  const shouldHideNavbar = hideNavbarOn.includes(pathname);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Provider store={store}>
        {!shouldHideNavbar && <Navbar />}
        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </Provider>
        
      </body>
    </html>
  );
}
